### PR TITLE
Stats loading

### PR DESCRIPTION
**Pull request by allengu01**
I have no idea if this is the best way to do it, but I think it works...

This seems like it's the more correct way to do it, but I couldn't get it to work :( https://trpc.io/docs/reactjs/useinfinitequery#getinfinitedata

### CODE REVIEW

**Comment by MeshanKhosla** [comment]
Yeah this looks great. What's the date input for? I don't see any change when I select a different date

**Comment by allengu01** [comment]
It should set the start date for the time range - it's been working for me, does it not work for you?

https://user-images.githubusercontent.com/42553779/232376923-d2e50380-c825-4150-b42e-e83c018e5848.mov

**Comment by MeshanKhosla** [comment]
> It should set the start date for the time range - it's been working for me, does it not work for you?
> Screen.Recording.2023-04-16.at.9.17.24.PM.mov

Ah it looks like datepicker is not supported in firefox. It's fine, the main functionality still works

**Review by MeshanKhosla — APPROVED** [review]
Nice!

**Pull request merged**
